const mongoose = require('mongoose')
const heroeSchema = mongoose.Schema({
    name:String,
    slug:String,
    tokenAsociado:String,
    "powerstats/intelligence":String,
    "powerstats/strength": String,
    "powerstats/speed": String,
    "powerstats/durability": String,
    "powerstats/power": String,
    "powerstats/combat": String,
    "appearance/gender": String,
    "appearance/race": String,
    "appearance/height/0":String,
    "appearance/height/1": String,
    "appearance/weight/0": String,
    "appearance/weight/1":String,
    "appearance/eyeColor": String,
    "appearance/hairColor": String,
    "biography/fullName":String,
    "biography/alterEgos": String,
    "biography/aliases/0": String,
    "biography/placeOfBirth":String,
    "biography/firstAppearance": String,
    "biography/publisher": String,
    "biography/alignment": String,
    "work/occupation": String,
    "work/base": String,
    "connections/groupAffiliation":String,
    "connections/relatives": String,
    "images/xs": String,
    "images/sm": String,
    "images/md": String,
    "images/lg": String,
    "biography/aliases/1": String,
    "biography/aliases/2": String,
    "biography/aliases/3": String,
    "biography/aliases/4": String
})

module.exports = mongoose.model("heroe",heroeSchema)
